language: python

cache: pip

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27

        - os: linux
          python: 3.5
          env: TOXENV=py35

        - os: linux
          python: 3.6
          env: TOXENV=py36

        - os: linux
          dist: xenial
          python: 3.7
          env: TOXENV=py37

        - os: linux
          dist: xenial
          python: 3.8-dev
          env: TOXENV=py38

        - os: linux
          python: 3.6
          env: TOXENV=cov
          after_success:
              - travis_retry pip install pytest-cov coveralls --upgrade
              - python setup.py test --addopts "-v --cov simplesqlite --cov-report term-missing"
              - coveralls

        - os: osx
          language: generic
          env: TOXENV=py36

install:
    - travis_retry bash -x .travis/install.sh

script:
    - bash -x .travis/run_test.sh

notifications:
    slack:
        secure: HwqLrkYmcRsUfwk6ufHWQjHACDkv4PE4QZCmxJVQtfqVWvT0Bk988xcpk+f76il6EX2x1aWLh1kox/2psU7wXGgBo83xW34xuF0rSR1Z+0JDi3IRefDdqf0QbE//x393ObchDRP8MiBce1oRpa26PK7ldUhorMBB14ueOgGtYhjSBI4xbTSP/enXPaOhrWwDL9Py5bkcVP2QyU2gv9PWMrXx69FYEPwRbUIlc5v1Ria/jT8Xrl186OwjyDTReYXyKDaK7cAfkpDjfl4UVTAglPJ9pBbZ82tPGxquop7gI9dZvgOb4CYeLncTg+MU9stu/L+xVdvZTDsl1bJtdtwVYpjVzVwsjM0/1mvxnDtit3OpHQBPkwJ0vPJUP3hiF6TqxhOK1JHzKB4/UVGo9vWRQ/4hXWPYsBjg+argCF5vf6oYdiEFVkytp/PhmNwWsBmVdtIjrapxBsYz1RBXDd2lBxMRXPkJk8zmS9/GNv5VXnEoLZqR/YlbAnBo3SQd91Sv14ExPRHFNsLCTtPN03pYw7RrSqYsyFRv2kn5O7I9nEvAFSsIaDwe1RCxk4L9QZVYOOpxygIduAVOuiQTYya2IpXzVCYmzZ/TgqbUSwEmPEH+BLcNj31wm+rVVluxzC0y4Vnn/QX1icF4bILHJH15w8lwas+LhLOTmb0WUhxsDPk=
